name: Build Python for Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/ader1990/cpython']
        python-branch: ['v3.8.6']
        python-arch: ['x64']

    steps:
      - name: Compile Python
        run: |
          git clone ${{ matrix.python-remote }}
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}

      - name: Create zip
        shell: cmd
        run: |
          mkdir cpython\PCBuild\${{ matrix.python-arch }}\lib
          mkdir cpython\PCBuild\${{ matrix.python-arch }}\include
          mkdir cpython\PCBuild\${{ matrix.python-arch }}\libs
          
          xcopy /i /e cpython\lib\*.* cpython\PCBuild\arm64\lib
          xcopy /i /e cpython\include\*.* cpython\PCBuild\arm64\include
          xcopy /i /e cpython\PC\pyconfig.h cpython\PCBuild\arm64\include
          xcopy.exe /y "cpython\PCBuild\arm64\python*.lib" "cpython\PCBuild\arm64\libs\"

      - uses: actions/upload-artifact@v1
        with:
          name: cpython-${{ matrix.python-arch }}
          path: cpython\PCBuild\${{ matrix.python-arch }}
