name: Build Python for Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/ader1990/cpython']
        python-branch: ['v3.9.0']
        python-arch: ['x86']
        python-dir: ['x86']

    steps:
      - name: Compile Python
        run: |
          git clone ${{ matrix.python-remote }}
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}

      - name: Create zip
        shell: cmd
        run: |
          mkdir cpython\PCBuild\${{ matrix.python-dir }}\lib
          mkdir cpython\PCBuild\${{ matrix.python-dir }}\include
          mkdir cpython\PCBuild\${{ matrix.python-dir }}\libs
          
          xcopy /i /e cpython\lib\*.* cpython\PCBuild\${{ matrix.python-dir }}\lib
          xcopy /i /e cpython\include\*.* cpython\PCBuild\${{ matrix.python-dir }}\include
          xcopy /i /e cpython\PC\pyconfig.h cpython\PCBuild\${{ matrix.python-dir }}\include
          xcopy.exe /y "cpython\PCBuild\${{ matrix.python-dir }}\python*.lib" "cpython\PCBuild\${{ matrix.python-dir }}\libs\"

      - uses: actions/upload-artifact@v1
        with:
          name: cpython-${{ matrix.python-branch }}-${{ matrix.python-arch }}
          path: cpython\PCBuild\${{ matrix.python-dir }}
